### ISSUE TITLE
umm...

### ISSUE THREAD

**Issue by starterdragon** [caspervanneck/bigbrother-15.0-en-15.1-end-1.8#1]
Warning: Declaration of shoghicp\BigBrother\DesktopPlayer::sendChunk($x, $z, $payload) should be compatible with pocketmine\Player::sendChunk($x, $z, $payload, $ordering = pocketmine\network\protocol\FullChunkDataPacket::ORDER_COLUMNS) in D:\TESTSERVER - Copy\plugins\bigbrother-15.0-en-15.1-end-1.8-MasterlazorX-php7\src\shoghicp\BigBrother\DesktopPlayer.php on line 0

Fatal error: Cannot override final method pocketmine\Player::close() in D:\TESTSERVER - Copy\plugins\bigbrother-15.0-en-15.1-end-1.8-MasterlazorX-php7\src\shoghicp\BigBrother\DesktopPlayer.php on line 0

**Comment by caspervanneck** [comment]
not done jet
